export const categories = [
    "Today's Picks",
    "Electronics",
    "Vehicles",
    "Property Rentals",
    "Apparel",
    "Classifieds",
    "Entertainment",
    "Family",
    "Free Stuff",
    "Garden & Outdoor",
    "Hobbies",
    "Home Goods",
    "Home Improvement",
    "Home Sales",
    "Musical Instruments",
    "Office Supplies",
    "Pet Supplies",
    "Sporting Goods",
    "Toys & Games",
    "Buy and sell groups",
  ];